map/urls.py
from django.conf.urls import url

from . import views

app_name = 'map'

urlpatterns = [
    url(r'^mainMap/$', views.mainMap, name='mainMap'),
]

tethys/urls.py
from django.conf.urls import include, url, handler400, handler403, handler404, handler500
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^map/', include('map.urls'), name='map'),
    url(r'^timeSeries/', include('timeSeries.urls'), name='timeSeries'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls'), name='main'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
]

handler400 = 'tethys.errorViews.badRequest400'
handler403 = 'tethys.errorViews.forbidden403'
handler404 = 'tethys.errorViews.notFound404'
handler500 = 'tethys.errorViews.serverError500'

# Ensures the introduction of basic entries into the database
from tethys import startup
startup.prepareTethys()

timeSeries/urls.py
from django.conf.urls import url
from timeSeries import views

app_name = 'timeSeries'

urlpatterns = [
    url(r'^select/series/(?P<seriesList>.+)/$', views.viewSeries, name='selectTimeSeries'),
    url(r'^deleteValues/series/(?P<seriesName>.+)$', views.deleteTimeSeries, name='deleteTimeSeries'),
    url(r'^upload/series/(?P<seriesName>.+)/uploadTimeSeries/$', views.uploadTimeSeries, name='uploadTimeSeries'),
    url(r'^upload/series/(?P<seriesName>.+)/$', views.upload, name='upload'),
    url(r'^trainForecast/(?P<forecastName>.+)/forecast/$', views.forecast, name='forecast'),
    url(r'^trainForecast/(?P<forecastName>.+)/forecast/getTrainingPeriods/$', views.getTrainingPeriods, name='forecastTrainingPeriods'),
    url(r'^trainForecast/(?P<forecastName>.+)/hindcast/$', views.hindcast, name='hindcast'),
    url(r'^trainForecast/(?P<forecastName>.+)/train/$', views.trainForecastBase, name='train'),
    url(r'^trainForecast/(?P<forecastName>.+)/train/progress/$', views.trainForecastProgress, name='progress'),
    url(r'^trainForecast/(?P<forecastName>.+)/train/cancel/$', views.trainCancel, name='progress'),
    url(r'^satelliteStore/(?P<name>.+)/progress/$', views.storeSatelliteDataProgress, name='updateSatelliteProgress'),
    url(r'^satelliteStore/(?P<name>.+)/$', views.storeSatelliteData, name='storeSatelliteData'),
    url(r'^satelliteUpdate/(?P<name>.+)/$', views.updateSatelliteData, name='updateSatellite'),
    url(r'^satelliteGet/$', views.getSatelliteData, name='getSatellite'),
    url(r'^getValues/$', views.getValues, name='getValues'),
    
    url(r'^admin/location/addBatch/$', views.batchLocations, name='batchLocations'),
    url(r'^admin/location/addBatch/registerBatch/$', views.batchLocationsRegister, name='batchLocationsRegister'),
    url(r'^admin/location/example/$', views.batchLocationsDownloadExample, name='batchLocationsDownloadExample'),
    
    url(r'^admin/series/addBatch/$', views.batchSeries, name='batchSeries'),
    url(r'^admin/series/addBatch/registerBatch/$', views.batchSeriesRegister, name='batchSeriesRegister'),
    url(r'^admin/series/example/$', views.batchSeriesDownloadExample, name='batchSeriesDownloadExample'),
    
    url(r'^admin/values/addBatch/$', views.batchValues, name='batchValues'),
    url(r'^admin/values/addBatch/registerBatch/$', views.batchValuesRegister, name='batchValuesRegister'),
    url(r'^admin/values/example/$', views.batchValuesDownloadExample, name='batchValuesDownloadExample'),
    url(r'^admin/values/addBatch/info/$', views.batchValuesInfo, name='batchValuesInfo'),
]

timeSeries/forms.py
import datetime as dt
from django import forms
from .models import Value, Series, Forecast


class UploadForm(forms.ModelForm):
    Series = forms.ModelChoiceField(queryset=Series.objects.all(), empty_label="(Select series)", to_field_name='name', label='',
                                    widget=forms.Select(attrs={'onchange':'getSeriesInfo();'}))
    
    class Meta:
        model = Series
        fields = ()
        
class ViewForm(forms.ModelForm):
    dateIni = forms.DateField(label='Start date', initial=dt.date.today)
    dateEnd = forms.DateField(label='End date', initial=dt.date.today)

    class Meta:
        model = Value
        exclude = ['date', 'record']
        
class ForecastForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(ForecastForm, self).clean()
        raise forms.ValidationError(
                    "Did not send for 'help' in the subject despite "
                    "CC'ing yourself."
                )

    class Meta:
        model = Forecast
        exclude = [];

timeSeries/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.conf import settings
from django_countries import countries
from timeSeries.models import Series, Value, Forecast, SatelliteData, Location, DataProvider, DataType, User
from .decoder import decode
#===============================================================================
# from django.utils.safestring import mark_safe
#===============================================================================
from django.core.files.base import ContentFile
from django.core.urlresolvers import reverse
from celery import task, current_task
from celery.result import AsyncResult
from djcelery.models import PeriodicTask, IntervalSchedule
from gpu.manager import Manager, getResampledTime, getDateList, fGenerateLeads, fSecond, fMinute, fHour, fDay, fWeek, fMonth, fYear
from . import satelliteData #@UnusedImport
from django.core.exceptions import ObjectDoesNotExist
from django_countries import countries

import binascii
import json
import warnings
import os
import datetime as dt
import dateutil.parser
import sys

import numpy as np
import matplotlib.pyplot as plt
import mpld3
from gpu.functions import plotQQ, ClickInfo
from timeSeries.uploadValues import uploadValues

def viewSeries(request, seriesList):
    context = {'LANG': request.LANGUAGE_CODE,
               'LOCAL_JAVASCIPT': settings.LOCAL_JAVASCIPT,
               }
    seriesDict = {}
    errorsDict = {'missing': list(),
                  'noAccess': list(),
                  'noData': list(),
                  }
    
    seriesList=seriesList.split('/')
    
    # find recent dates
    recentDates = []
    for seriesName in seriesList:
        tmpResult = Series.objects.filter(name=seriesName)
        if len(tmpResult)>0:
            s0 = tmpResult[0]
            recentDates.append(Value.objects.filter(series=s0.id).order_by('date').last().date)
    recentDate = max(recentDates)
    recentDate = recentDate.replace(year=recentDate.year-2)
    
    # retrieve series' info
    for seriesName in seriesList:
        tmpResult = Series.objects.filter(name=seriesName)
        if len(tmpResult)>0:
            s0 = tmpResult[0]
            result = Value.objects.filter(series=s0.id).order_by('date')
            if tmpResult[0].encryptionKey==None:
                values = [{'x':obj.date.isoformat(), 'y':str(obj.recordOpen)} for obj in result.filter(date__gte=recentDate)]
            else:
                values = [{'x':obj.date.isoformat(), 'y':binascii.b2a_base64(obj.record).decode("utf-8")} for obj in result.filter(date__gte=recentDate)]
            
            forecasts = {}
            for f0 in Forecast.objects.filter(targetSeries=s0.id).filter(ready=True):
                forecasts[f0.name] = {}
                forecasts[f0.name]['urlForecast'] = '/timeSeries' + reverse('forecast', 'timeSeries.urls', kwargs={'forecastName': f0.name})
                forecasts[f0.name]['urlHindcast'] = '/timeSeries' + reverse('hindcast', 'timeSeries.urls', kwargs={'forecastName': f0.name})
                forecasts[f0.name]['description'] = f0.description
                forecasts[f0.name]['leadTime'] = f0.leadTime
                forecasts[f0.name]['seasons'] = f0.splitBySeason
            
            if s0.location.country in dict(countries):
                tmpCountry = dict(countries)[s0.location.country]
            else:
                tmpCountry = ''
            tmp = {'id': s0.id,
                'name': s0.name,
                'type': s0.type.name,
                'provider': s0.provider.name,
                'providerAbbreviation': s0.provider.abbreviation,
                'providerIcon': '/' + str(s0.provider.icon),
                'providerWebpage': s0.provider.website,
                'units': s0.type.units,
                'typeIcon': '/' + str(s0.type.icon),
                'lat': float(s0.location.lat),
                'lon': float(s0.location.lon),
                'location': s0.location.name,
                'quality': s0.quality,
                'timeStepUnits': dict(Series.TIME_STEP_PERIOD_TYPE)[s0.timeStepUnits],
                'timeStepPeriod': s0.timeStepPeriod,
                'encryptionKey': s0.encryptionKey,
                'metaEncrypted': s0.metaEncrypted,
                'river': s0.location.river,
                'country': tmpCountry,
                'catchment': s0.location.catchment,
                'values': values,
                'records': len(result),
                'forecasts': forecasts,
                }
               
            if len(result)==0:
                errorsDict['noData'].append(seriesName)
                tmp.update({'minDate': '',
                            'maxDate': ''})  
            else:
                tmp.update({'minDate': result.first().date.isoformat(),
                            'maxDate': result.last().date.isoformat()})     
            seriesDict[str(s0)] = tmp
        else:
            errorsDict['missing'].append(seriesName)
        
    context['series'] = json.dumps(seriesDict)
    context['errors'] = json.dumps(errorsDict)
    
    # fields
    fields = (('Id', 'name'),
              ('Location', 'location'),
              ('River', 'river'),
              ('Catchment', 'catchment'),
              ('Type', 'type'),
              ('Units', 'units'),
              ('Time step', 'timeStepUnits'),
              ('Records', 'records'),
              ('From', 'minDate'),
              ('To', 'maxDate'),
              )
    context['fields'] = json.dumps(fields)
    
    return render(request, 'timeSeries/viewSeries.html', context)

def deleteTimeSeries(request, seriesName):
    series = Series.objects.filter(name=seriesName)
    if len(series)==0:
        context = {'message': ('error', 'The series ' + seriesName + ' has not been found in the database.')}
    else:
        tmp = Value.objects.filter(series=series).count()
        if tmp>0:
            Value.objects.filter(series=series).delete()
            context = {'message': ('success', str(tmp) + ' records successfully deleted.')}
        else:
            context = {'message': ('warning', 'No data to be deleted.')}

    return HttpResponse(
                        json.dumps(context),
                        content_type="application/json"
                        )
    
def upload(request, seriesName):
    series = Series.objects.filter(name=seriesName)
    if series:
        provider = series[0].provider
        location = series[0].location
        seriesType = series[0].type        
        
        result = Value.objects.filter(series=series[0].id).order_by('date')
        values = [{'x':obj.date.isoformat(), 'y':binascii.b2a_base64(obj.record).decode("utf-8")} for obj in result]
        
        context = {'LANG': request.LANGUAGE_CODE,
                   'series': series[0].name,
                   'encryptionKey': series[0].encryptionKey,
                   'metaEncrypted': series[0].metaEncrypted,
                   'timeStep': dict(Series.TIME_STEP_PERIOD_TYPE)[series[0].timeStepUnits],
                   'timeStepPeriod': series[0].timeStepPeriod,
                   'provider': str(provider),
                   'type': str(seriesType),
                   'units': seriesType.units,
                   'location': str(location),
                   'data': json.dumps(values),
                   'LOCAL_JAVASCIPT': settings.LOCAL_JAVASCIPT,
                   }
        return render(request, 'timeSeries/uploadValues.html', context)
    else:
        return HttpResponseNotFound('Series [' + seriesName + '] not found...')

def uploadTimeSeries(request, seriesName):
    # TODO: check provider pass
    # TODO: check duplicated values
    
    data = json.loads(request.POST.get('toUpload'))
    seriesObj = Series.objects.get(name=seriesName)
    
    warnings.filterwarnings('ignore', '.*Invalid utf8 character string.*',)
    
    toInput = list()
    for i0, d0 in enumerate(data):
        toInput.append(Value(series=seriesObj, date=d0['date'][:-1], record=binascii.a2b_base64(d0['value'])))
        if i0 % 1000==0 and i0!=0:
            Value.objects.bulk_create(toInput)
            toInput = list()
    Value.objects.bulk_create(toInput)
    
    context = {'message': 'done!'}
    return HttpResponse(
                        json.dumps(context),
                        content_type="application/json"
                        )

def seriesData(request):
    context = {}
    if request.method == 'POST':
        seriesObj = Series.objects.get(name=request.POST.get('series'))
        provider = seriesObj.provider
        location = seriesObj.location
        seriesType = seriesObj.type
        context = {'location': str(location),
                   'provider': str(provider),
                   'type': str(seriesType),
                   'units': seriesType.units,
                   'timeStepUnits': dict(Series.TIME_STEP_PERIOD_CHOICES)[seriesObj.timeStepUnits],
                   'timeStepPeriod': seriesObj.timeStepPeriod,
                   'metaEncrypted': seriesObj.metaEncrypted,
                   'encryptionKey': seriesObj.encryptionKey,
                   'name': seriesObj.name,
                   }
        return HttpResponse(
                            json.dumps(context),
                            content_type="application/json" 
        )

def getValues(request):
    context = {}
    if request.method == 'POST':
        s0 = Series.objects.get(name=request.POST.get('series'))
        #=======================================================================
        # dateFrom = dt.datetime.strptime(request.POST.get('from').split(',')[1][1:], "%d %b %Y %H:%M:%S %Z").replace(tzinfo = None)
        # dateTo = dt.datetime.strptime(request.POST.get('to').split(',')[1][1:], "%d %b %Y %H:%M:%S %Z").replace(tzinfo = None)
        #=======================================================================

timeSeries/templates/timeSeries/batchLocations.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset=utf-8>
		<title>Tethys: Water Resources Database Locations Upload</title>
		<link rel="icon" type="image/png" href="{% static 'main/images/icon.png' %}" />
		
		{{ LOCAL_JAVASCIPT|safe }}
        
        <script src="{% static 'timeSeries/scripts/ajax.js' %}"></script>
        <script src="{% static 'timeSeries/scripts/xlsx.core.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'timeSeries/scripts/datatables.min.js' %}"></script>
        
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'main/css/jquery-ui.css' %}" /> -->
		<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}" />
    	<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'timeSeries/css/datatables.min.css' %}"/>
		
	<style>
	.loader {
		height: 80px;
		background-image: url("{% static 'main/images/loader.gif' %}");
		background-repeat: no-repeat;
		background-position: center center;
	}
	
	#download {
		background: #79aec8;
		font-size: 13px;
	}
	
	#deleteP {
		float: right;
	}
	
	.warning {
		background: aqua;
	}
	
	.error {
		background: red;
	}
	</style>
	
	</head>
	<body>
		<div>
    		<div id="header">
        		<div id="branding">
					<h1 id="site-name">Tethys administration</h1>
        		</div>
    	    </div>
		</div>
		
		<div class="breadcrumbs">
			Add multiple locations from an Excel spreadsheet
		</div>
		
		<div id="content" class="colM">
			<div id="content-main">
				<fieldset class="module aligned ">
					<h2>1. Import</h2>
					<div class="description">Import the Excel file with the location information.</div>
					<input value="Browse..." name="_upload" type="file" id="choose">
				</fieldset>
				
				<fieldset class="module aligned" id="validate">
					<h2>2. Validate and upload</h2>
					<div class="description">Process and validate the data, then proceed with the upload. May take some time. Please be patient.</div>
					<div id="excelLoader" class="loader"></div>
					<div id="dataTableWrapper"></div>
				</fieldset>
				
				<div class="submit-row">
					<form onsubmit="return submit();" method="post" id='upload'>
			    		{% csrf_token %}
			    		<input value="Save new locations" class="default" name="_save" type="submit" id="uploadPostButton">
					</form>
					<p class="deletelink-box" id="upload"><a id="download" href="/timeSeries/admin/location/example/" class="deletelink">Download example</a></p>
				    </div>
			</div>
		</div>
		
		<script>
			// prepare page
			$(document).ready(function() {
				$('#download').parent().css("float","right")
				
				$('#validate').hide();
				$('#upload').hide();
				
				//$('#"errors"').hide();
				//$('#"warnings"').hide();
				//$('.loader').hide();
				
			})
			
			// Object prototype
			function Location(name, lat, lon, catchment, river, country, observations) {
				this.Name = name;
			    this.Latitude = lat;
			    this.Longitude = lon;
			    this.Catchment = catchment;
			    this.River = river;
			    this.Country = country;
			    this.Observations = observations;
			    
			    this.Status = '';
			}
			
			var dataToUpload;			
			function handleExcelFile(e) {
		  		//$('#excelLoader').show();
		  		//$('#errors').hide();
		  		//$('#warnings').hide();
		  		
		  		dataToUpload = [];
				setTimeout(
						function() {
							var files = e.target.files;
							var reader = new FileReader();
							//var name = files[0].name;
							reader.onload = function(e) {
								$('#validate').show();
								$('#excelLoader').show();
								$('#dataTableWrapper').hide();
								
								var data = e.target.result;

								var workbook = XLSX.read(data, {
									type : 'binary'
								});
								var sheetNameList = workbook.SheetNames;
								var worksheet = workbook.Sheets[sheetNameList[0]];
								console.log(worksheet);
								var cellref;
								var header = true;
								var tmpName = null;
								var tmpLat = null;
								var tmpLon = null;
								var tmpCatchment = null;
								var tmpRiver = null;
								var tmpCountry = null;
								var tmpObservations = null;
								for (cellref in worksheet) {
									
									if (cellref[0] != '!') {
											if (cellref.toString() === 'A2' || !header) {
												header = false;
												if (cellref.toString().indexOf('A') === 0) {
													if (cellref.toString() != 'A2') {
														dataToUpload.push(new Location(
																tmpName, tmpLat,
																tmpLon, tmpCatchment,
																tmpRiver, tmpCountry,
																tmpObservations));
														
														tmpName = null;
														tmpLat = null;
														tmpLon = null;
														tmpCatchment = null;
														tmpRiver = null;
														tmpCountry = null;
														tmpObservations = null;
													}
													tmpName = worksheet[cellref].v;
												}
												if (cellref.toString().indexOf('B') === 0) {
													tmpLat = parseFloat(worksheet[cellref].v);
												}
												if (cellref.toString().indexOf('C') === 0) {
													tmpLon = parseFloat(worksheet[cellref].v);
												}
												if (cellref.toString().indexOf('D') === 0) {
													tmpCatchment = worksheet[cellref].v;
												}
												if (cellref.toString().indexOf('E') === 0) {
													tmpRiver = worksheet[cellref].v;
												}
												if (cellref.toString().indexOf('F') === 0) {
													tmpCountry = worksheet[cellref].v;
												}
												if (cellref.toString().indexOf('G') === 0) {
													var tmpObservations = worksheet[cellref].v;
												}
											}
										}
									}
									if (tmpName!=null) {
										dataToUpload.push(new Location(
												tmpName, tmpLat,
												tmpLon, tmpCatchment,
												tmpRiver, tmpCountry,
												tmpObservations));
									}
								};
								reader.onloadend = function() {
									createTable(dataToUpload);
								};
								
								reader.readAsBinaryString(files[0]);
						}, 0);
			}
			
			function createTable(tableData) {
				$('#dataTableWrapper').html('');
				var table = document.createElement('table');
				var tableHead = document.createElement('thead');
				var properties = Object.getOwnPropertyNames(new Location());
				var header = document.createElement('tr');
				properties.forEach(
						function(property) {
							var cell = document.createElement('th');
							cell.appendChild(document.createTextNode(property));
							header.appendChild(cell);
						});
				tableHead.appendChild(header);
				table.appendChild(tableHead);
				
				var tableBody = document.createElement('tbody');
				tableData.forEach(
						function(rowData) {
							var row = document.createElement('tr');
							properties.forEach(
									function(property) {
										var cell = document.createElement('td');
										if (rowData[property] === null) {
											cell.appendChild(document.createTextNode(''));
										} else {
											cell.appendChild(document.createTextNode(rowData[property]));
										}
										row.appendChild(cell);
									});
							tableBody.appendChild(row);
						});
				table.appendChild(tableBody);
				
				$('#dataTableWrapper').html(table);
				$('#dataTableWrapper').find('table').DataTable({
					"createdRow": function(row, data, dataIndex) {
						if (data[data.length-1].indexOf('!Warning: ') === 0) {
							$(row).css('background', '#ffefb4');
						} else if (data[data.length-1] != 'Success' && data[data.length-1] != '') {
							$(row).css('background', '#ffbfb4');
						}
					},
					"order": [[ properties.length-1, "asc" ]],
				});
				$('#dataTableWrapper').find('input').css('float', 'right');
				
				$('#excelLoader').hide();
				$('#dataTableWrapper').show();
				$('#upload').show();
			}

			$('#choose').get()[0].addEventListener('change', handleExcelFile, false);
		</script>
		
		<script>
			// encrypt and upload data
			$('#uploadPostButton').on('click', function(event){
				event.preventDefault();
				
				$('#excelLoader').show();
				$('#dataTableWrapper').hide();
				$('#upload').show();
				
				// send data
				$.ajax({
					url : "registerBatch/",
					type : "POST",
					data : {
						elements: JSON.stringify(dataToUpload),
					},
			
					// handle a successful response
					success : function(json) {
						var success = json.success;
						var warnings = json.warnings;
						var errors = json.errors;
						
						for (var i0=0; i0<success.length; i0++) {
							dataToUpload[success[i0][0]].Status = success[i0][1];
						}
						for (var i0=0; i0<warnings.length; i0++) {
							dataToUpload[warnings[i0][0]].Status = '!Warning: duplicate entry';
						}
						for (var i0=0; i0<errors.length; i0++) {
							dataToUpload[errors[i0][0]].Status = '!Error: ' + errors[i0][1];
						}
						
						createTable(dataToUpload);
					},
		
					// handle a non-successful response
					error : function(xhr,errmsg,err) {
						console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
						$('#excelLoader').hide();
					}
				});
			});
		</script>
	</body>
</html>

timeSeries/templates/timeSeries/upload.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset=utf-8>
		<title>Tethys: Water Resources Database Series Upload</title>
		<link rel="icon" type="image/png" href="{% static 'main/images/icon.png' %}" />
		
		{{ LOCAL_JAVASCIPT|safe }}
        
        <script src="{% static 'timeSeries/scripts/ajax.js' %}"></script>
		<script src="{% static 'timeSeries/scripts/forge.min.js' %}"></script>
		
        <script src="{% static 'timeSeries/scripts/xlsx.core.min.js' %}"></script>
        
        <script src="{% static 'timeSeries/scripts/d3.min.js' %}"></script>
        <script src="{% static 'timeSeries/scripts/d3.layout.min.js' %}"></script>
        <script src="{% static 'timeSeries/scripts/rickshaw.min.js' %}"></script>
        
        <script src="{% static 'timeSeries/scripts/plotChart.js' %}"></script>
        
		<!--<link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'main/css/jquery-ui.css' %}" />-->
		
		<link rel="stylesheet" type="text/css" href="{% static 'timeSeries/css/rickshaw.min.css' %}" />
		
		<link rel="stylesheet" type="text/css" href="{% static 'timeSeries/css/chart.css' %}" />
		
		<style>
			body {
				overflow: hidden;
			}
		</style>
		
	</head>
	<body>
		<script>
			/*var seriesData;
			var seriesInfo = {name: 'Name',
							location: 'Location',
							type: 'Type',
							units: 'Units',
							timeStepUnits: 'Time step',
							provider: 'Provider',
							encryptionKey: 'encryptionKey',
							};
			
			function fBuildTable(dataObj) {
				var table = '<table id="seriesInfoTable"><tr>';
				for (k0 in seriesInfo) {
					table += '<th>' + seriesInfo[k0] + '</th>';
				}
				table += '</tr><tr>';
				for (k0 in seriesInfo) {
					table += '<td>' + dataObj[k0] + '</td>';
				}
				table += '</tr></table>';
				$('#seriesInfo').append(table);
			}
		
			// get information from the chosen series
			function getSeriesInfo() {
				$('#seriesInfo').empty();				
				if ($('#id_Series').val() != '') {			
					$.ajax({
				        url : "upload/seriesData", // the endpoint
				        type : "POST", // http method
				        data : {series: $('#id_Series').val(),}, // data sent with the post request
		
				        // handle a successful response
				        success : function(json) {
							seriesData = json;
				            fBuildTable(seriesData);
				        },
				        // handle a non-successful response
				        error : function(xhr,errmsg,err) {
				            $('#seriesInfo').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
				                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
				            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
				        }
				    });
				}				
			}*/
		</script>
		
		<input id="series" type="file" name="file">
		<div id="chart"></div> 
		<div id="slider"></div>
		<form action="upload/" method="post" id='uploadPost'>
		    {% csrf_token %}
		    {{ form }}
		    <input type="submit" value="Submit" id='uploadPostText'/>
		</form>
		
		<script>
			var dates;
			var records;
		  	function handleFile(e) {
				dates = [];
				records = [];
									
		  		var files = e.target.files;
		  		var i,f;
		  		for (i = 0, f = files[i]; i != files.length; ++i) {
		    		var reader = new FileReader();
		    		var name = f.name;
		    		reader.onload = function(e) {
		      			var data = e.target.result;
		
		      			var workbook = XLSX.read(data, {type: 'binary'});
		      			var sheetNameList = workbook.SheetNames;
				      	var worksheet = workbook.Sheets[sheetNameList[0]];
						
						var tmpDate;
						var dataForDisplay = [];
				  	   	for (z in worksheet) {
					    	if(z[0] != '!') {
								if (z.toString().indexOf('A') === 0) {
									tmpDate = Date.parse(worksheet[z].v);
									dates.push(tmpDate);
								}
								if (z.toString().indexOf('B') === 0) {
									var tmpRecord = parseFloat(worksheet[z].v);
									dataForDisplay.push(new Point(tmpDate, tmpRecord));
									records.push(tmpRecord);
									tmpDate = null;
								}
							}
					  	}
					  	
					  	// display plot
					  	
					  	for (i0=0; i0<dates.length; i0++) {
							dataForDisplay.push(new Point(dates[i0], records[i0]));
						}		
					  	
					  	$('#uploadPost').show();
					  	display(dataForDisplay);
					  	
		    		};
		    		reader.readAsBinaryString(f);
		  		}
			}
			$('#series').get()[0].addEventListener('change', handleFile, false);
			
			$(document).ready(function() {
				$('#uploadPost').hide();
				
				if ('{{ metaEncrypted }}' === 'True') {
					console.log('meta');
				} else {
					console.log('not meta');
				}
			})
		</script>
	</body>
</html>